print("     *")
print("    * *")
print("   *   *")
print(" *      *")
print("***    ***")
print(" *      *")
print(" *      *")
print(" *      *")
print(" ********")
print("           *   ")
print("         *   *  ")
print("       *      * ")
print("      *        * ")
print("     *          *")
print("    ***        ***")
print("     *          * ")
print("     *          * ")
print("     *          * ")
print("     ************ ")
print("           *              *", "         *   *          *   *", "       *      *        *     *", "      *        *      *       *", "     *          *    *         *", "    ***        ***  ***       ***", "     *          *    *         *", "     *          *    *         *", "     *          *    *         *", "     ************    ***********", sep="\n")