nombre=input("Ingrese el nombre completo del usuario: ")
print(nombre*3)
print("     * ")
print("    * *")
print("   *   *")
print(" *      *")
print("***    ***")
print(" *      *")
print(" *      *")
print(" *      *")
print(" ********")
